# Generated by Django 4.0.5 on 2022-07-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thetracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setter',
        ),
    ]
